version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3.1.3
# workflows:
#   build:
#     jobs:
#       # "run" job comes from "cypress" orb
#       - cypress/run:
#           cypress-command: npm run cypress:run-allure:ci
#           install-browsers: true
#           # start-command: 'npm run cypress:run-allure:ci'
jobs:
  run-test-and-notify:
    # Steps to the job
    steps:
      - checkout
      - run:
          name: Download dependency
          environment:
            SECRET_KEY: SECRET_KEY
          command: npm ci
      - run:
          name: Run tests
          command: npm run cypress:run-allure:ci
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: /root/project/cucumber-report.html
          destination: cucumber-report.html
      - store_artifacts:
          path: /root/project/cypress/videos
          destination: videos
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          mentions: "@junhao.hu"
          template: basic_fail_1
      - twilio/sendsms:
          body: Cypress automation test successful - from Twilio
      - twilio/alert:
          body: Cypress automation test failed - from Twilio
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test-and-notify